{% set version = "1.2.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-svmisc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/svMisc_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/svMisc/svMisc_{{ version }}.tar.gz
  sha256: 2dd52147981b51a15071b4cd77a87f790edac77bc215dbbea59764bb0a8c73e4

build:
  merge_build_host: true  # [win]
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('svMisc')"           # [not win]
    - "\"%R%\" -e \"library('svMisc')\""  # [win]

about:
  home: https://github.com/SciViews/svMisc, http://www.sciviews.org/SciViews-R
  license: GPL-2.0-only
  summary: 'Miscellaneous functions for SciViews or general use: manage a temporary environment attached to the search path for temporary variables you do not want to save() or load(), test if Aqua, Mac, Win, ... Show progress bar, etc.'
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: svMisc
# Type: Package
# Version: 1.1.0
# Date: 2018-06-10
# Title: SciViews - Miscellaneous Functions
# Description: Miscellaneous functions for SciViews or general use: manage a temporary environment attached to the search path for temporary variables you do not want to save() or load(), test if Aqua, Mac, Win, ... Show progress bar, etc.
# Authors@R: c(person("Philippe", "Grosjean", role = c("aut", "cre"), email = "phgrosjean@sciviews.org"), person("Romain", "Francois", role = "ctb", email = "romain@r-enthusiasts.com"), person("Kamil", "Barton", role = "ctb", email = "kamil.barton@uni-wuerzburg.de"))
# Maintainer: Philippe Grosjean <phgrosjean@sciviews.org>
# Depends: R (>= 2.13.0)
# Imports: utils, methods, stats, tools
# Suggests: rJava, tcltk, covr, knitr, testthat
# License: GPL-2
# URL: https://github.com/SciViews/svMisc, http://www.sciviews.org/SciViews-R
# BugReports: https://github.com/SciViews/svMisc/issues
# RoxygenNote: 6.0.1
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2018-06-27 13:02:33 UTC; phgrosjean
# Author: Philippe Grosjean [aut, cre], Romain Francois [ctb], Kamil Barton [ctb]
# Repository: CRAN
# Date/Publication: 2018-06-30 17:04:09 UTC
