appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: uKHunWa3nv+cxMeFkmvHO+j+dkWGQ9wnprJBUQNsKoygM6ab5r0BDA6gGzhD8RSbLCsKdQXYhISgYtN4+hDJnX+NfGoG3PD47/QdRXkyrpBrbarmOMFHs3jVWA5vuaJvBgKEdx580oWr77iXwjGmEzMXWlCquiR8ZbyrK7pzT2SEuV991Z8jxpBQPgd/01RhfRPykVUGW7YZ8/wBFdOIYWE1c/97gMIIrzKjNbdwE+VcD+sVG0kSY089x/XsiIy5hujespwzmn4tWeJKsEvyHDsRl7vyLSj49JSUerBw9YjbGYkTuzSBnJL/LUoRcNLaGUT7X8GDvhfkP6LcUo4ahqoZUOO2E/2yZE1kEFvjxvb2eLzt6iyYjiNHPFIuEZ2pZOznbKNPfVlDkSCYWf8o1k3Tkv+I85dXAQ0bP349y9jlvrs7QKI3fLs61l85iTWnfvAiNMuRsCW0mVU48GEm5hmwIOh26DLOvXMsWzV9/z0MrGE9gsyTwnVbGG5s5/Ovl/Afs7gR4jy7AY+B+bhJiaIqenB/V7Ke2bnQmDgBBCCMxWS5oRevO8aOj+5gqa22tLNZHmQOThF0fj92lwp2+YyTt5qV789O5qP9fdKY2r2OyV07BfEOLfJwFhJlYHulRJz/VDFylzgm9SPNJSSBNvZQ9TmQtIC+leIIvnJypPE=}
bot:
  automerge: true
