travis:
  secure:
    BINSTAR_TOKEN: q2rVZKGnmxH/MqmenhlBfTKCWcw6AoasytrpotC6wjAcBsniQ8216re8HnAGIYm/JAbW+kjLjmhLqTbZjgZXQ1T1p03W+SPzMaPRz692KXH2hiXlK3+iri/u0F7euit7deRf9NG51wLeuT3EPRYbSUaxrnc+KroUJoZCi5EtcT9I1Z3XI3EzwK/pWFX5yI0p/fTPTnCEwO6GQsxaqsxrCszJqxHBKQuik3MhAJosbYlcMIRhDTTMw9RmYgx6ha8zsGjh+49HuCI1FKSaFTGoWmMqCt2OBaXINcUxU9DQUtrp6QycRIxWYuOyHgK8LVVj96DAXOiCIuFKkoXZEg74ClC03ieiec6KKv4u3KZMjuJBDc+V6POcFQ70J2JwjoDSjx8bVsOzkPPn7SrtFkw7vQIvCNVYQlKywYDNQj6JNpedL/77SdKxNJWMXKSojCd81OnqVDo7tA6ozqMa23lDZGdYFp/FSbHVShKfgzIP1shiQD46+0+oQCggdJRDVe0goNVgwV8H9MDu0YTNt6HFn1W71yqLdXhJYXETmsZBW/2PVEBU+QVwH4uDgXVwEkhOsJqxWGL9NuJY+s1HwdL4Mlf8D7yG9aJzQHn/9gljaDdGNeHEBpBS8uNGmZA6LZ41Ks95CXIIH0zYyG9rymGeQ8JbqM6Ebu/bMCXB7/mdp5E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
